services: mongodb

sudo: false

language: ruby

cache: bundler

rvm:
  - 2.2
  - 2.1.1
  - 2.0.0
  - 1.9.3
  - jruby-19mode

allow_failures:
  - rvm: rbx-2

env:
  - MONGOID_VERSION=3
  - MONGOID_VERSION=4
  - MONGOID_VERSION=5
